/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AirPollution;

import com.google.gson.Gson;

public class App {

    public static void main(String[] args) {
        String stationsJson = "";

        Gson gson = new Gson();

        DataStation[] stations = gson.fromJson(stationsJson, DataStation[].class);

        for(DataStation station : stations) {
            System.out.println(station.id + ": " + station.stationName);
        }
    }

}
