/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AirPollution;

public class App {

    public static void main(String[] args) {
        try {
            System.out.println(URLReader.getHTML());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
